env: walker2d-medium-expert-v2
horizon: 600
max_path_length: 1000
state_dim: 17
action_dim: 6
diffusion_denoise_time_step: 20
diffusion_normalizer: GaussianNormalizer
value_normalizer: LimitsNormalizer
ema_decay: 0.995
train_batch_size: 32
train_lr: 0.0002
value_termination_penalty: -100.0
max_n_episode: 2190
safety: -5.9604645
score_mean: 0.6972416608271782
score_std: 0.11012075705761641
computation_time: 2.3315845727920532
