env: hopper-medium-replay-v2
horizon: 600
max_path_length: 1000
state_dim: 11
action_dim: 3
diffusion_denoise_time_step: 20
diffusion_normalizer: GaussianNormalizer
value_normalizer: LimitsNormalizer
ema_decay: 0.995
train_batch_size: 32
train_lr: 0.0002
value_termination_penalty: -100.0
max_n_episode: 2041
safety: 0.027892888
score_mean: 0.3628497536553125
score_std: 0.3383436043144587
computation_time: 1.9826076030731201
