env: walker2d-medium-v2
horizon: 600
max_path_length: 1000
state_dim: 17
action_dim: 6
diffusion_denoise_time_step: 20
diffusion_normalizer: GaussianNormalizer
value_normalizer: LimitsNormalizer
ema_decay: 0.995
train_batch_size: 32
train_lr: 0.0002
value_termination_penalty: -100.0
max_n_episode: 1190
safety: 0.0
score_mean: 0.5671394340359901
score_std: 0.3301327498630481
computation_time: 1.9196467638015746
