env: hopper-medium-v2
horizon: 600
max_path_length: 1000
state_dim: 11
action_dim: 3
diffusion_denoise_time_step: 20
diffusion_normalizer: GaussianNormalizer
value_normalizer: LimitsNormalizer
ema_decay: 0.995
train_batch_size: 32
train_lr: 0.0002
value_termination_penalty: -100.0
max_n_episode: 2186
safety: -5.9604645
score_mean: 0.4436594349500214
score_std: 0.22480364570693676
computation_time: 2.3017058849334715
